package model;
// Generated 07.08.2017 14:53:51 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Javascript generated by hbm2java
 */
@Entity
@Table(name = "javascript", catalog = "mydb")
public class Javascript implements java.io.Serializable {

	private int id;
	private String exampleName;
	private String description;

	public Javascript() {
	}

	public Javascript(int id, String exampleName, String description) {
		this.id = id;
		this.exampleName = exampleName;
		this.description = description;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "EXAMPLE_NAME", nullable = false, length = 200)
	public String getExampleName() {
		return this.exampleName;
	}

	public void setExampleName(String exampleName) {
		this.exampleName = exampleName;
	}

	@Column(name = "DESCRIPTION", nullable = false, length = 1000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
